### ISSUE TITLE
Setup bootstrap 

### ISSUE THREAD

**Issue by moein** [codenip-tech/brisbane#36]
Once #35 is done setup bootstrap in the project. Simple add the necessary css and js files in the layout.

**Comment by juanwilde** [comment]
Let's do this!! :)

**Comment by luisriego** [comment]
Ok! is done

**Comment by luisriego** [comment]
Juan, I think this issue is different to #35, because the issue#36 is for oauth service, while the issue#35 is for app service. Reconsider to open it again!

**Comment by juanwilde** [comment]
Hi Luis.
#35 is to just add webpack encore to OAuth server, while #36 is to add Bootstrap once webpack encore task is merged

**Comment by luisriego** [comment]
Juan, moein! How to commit my pr without create a new one?

**Comment by juanwilde** [comment]
You just need to checkout to your local branch and create there the new commits. You should have a local branch with the code for this task. Just add the changes there and push it to the remote branch. 
Anyway, tomorrow we will check again how to contribute :)

**Comment by juanwilde** [comment]
You only need to create the PR once. Then, every time you push new commits to it, approvals will be removed, pipeline re-triggered and we will be notified.
