### ISSUE TITLE
Add symfony binary installation in app php Dockerfile

### ISSUE THREAD

**Issue by lologalvez** [codenip-tech/brisbane#41]
Symfony binary installation is missing from app php Dockerfile which makes "symfony" executable command missing from path. It should be installed as in oauth php Dockerfile.

**Comment by juanwilde** [comment]
The App already has a Symfony installation and since it also contains a [web server](https://github.com/codenip-tech/brisbane/blob/2386e1d760b98e3b53436c56b3741562e2281228/app/docker-compose.yml#L4), having the Symfony binary is not needed anymore :)

**Comment by lologalvez** [comment]
I had an issue while executing "make logs" from app/Makefile: "symfony executable is not found in $PATH". But it also could be a missconfiguration from my side. Could you confirm? Thanks!

**Comment by juanwilde** [comment]
You are right. We have changed the Dockerfile but didn't update the Makefile. Would you like me to create a task for this and assign it to you??
